config/routes.rb
Rails.application.routes.draw do
  get "attendances/index"

  namespace :admin do
    # resources :users
    resources :students
    resources :teachers
    resources :parents
    resources :transports
    # resources :leave_request
    resources :securities
    resources :class_rooms
    resources :lactures
    resources :attendances
    root to: "students#index"
  end

  get "teachers/scaffold"
  get "students/index"
  get "students/new"
  get "students/edit"
  get "profiles/index"
  get "profiles/show"
  get "welcome/index"
  devise_for :users, controllers: {
    sessions: 'users/sessions' ,
    # Tell Devise to use the overridden controller
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :students
  resources :teachers
  resources :class_rooms
  resources :lactures do
    resources :attendances
  end
  
  resources :leave_requests do
    collection do
      post :apply_early_leave, to: 'leave_requests#create_early_leave'
      get  :apply_early_leave, to: 'leave_requests#apply_early_leave'
    end
    member do
      patch :update_status
      get :update_status  # temporary
    end
  end
  resources :profiles
  root "welcome#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
  belongs_to :lacture

  enum :status, {present: 0, absent: 1}
  STATUS_COLORS = {
    'present' => 'success',
    'absent' => 'danger'
  }.freeze
end

app/models/class_room.rb
class ClassRoom < ApplicationRecord
  has_many :students
  has_many :lactures
  enum :year, {first_year: 0, second_year: 1, third_year: 2, fourth_yaar: 3}
end

app/models/lacture.rb
class Lacture < ApplicationRecord
  belongs_to :teacher
  belongs_to :class_room
  has_many :attendances
end

app/models/leave_request.rb
class LeaveRequest < ApplicationRecord
  has_many :users, class_name: 'User', foreign_key: 'approval_id'
  belongs_to :user

  enum :status, { pending: 0, approved: 1, cancelled: 2 }
  enum :leave_type, {full_day: 0, half_day: 1}
  enum :transport, {College_transport: 0, own_vahicle: 1}

  STATUS_COLORS = {
    'approved' => 'success',
    'pending' => 'warning',
    'cancelled' => 'danger'
  }.freeze

  after_create :send_email_for_approval

  def send_email_for_approval
    UserMailer.send_email_for_approval(self, User.admin_user).deliver_now
  end
end

app/models/parent.rb
class Parent < User
  has_many :students
end

app/models/security.rb
class Security < User
end

app/models/student.rb
class Student < User
  belongs_to :parent, optional: true
  belongs_to :class_room, optional: true
  has_many :attendances

  def parent_email
    parent&.email
  end

  def parent_email=(email)
    found_parent = Parent.find_by(email: email)
    if found_parent
      self.parent = found_parent
    else
      errors.add(:parent_email, "not found")
    end
  end
end

app/models/super_admin.rb
class SuperAdmin < User
end

app/models/teacher.rb
class Teacher < User
  has_many :lactures
end

app/models/transport.rb
class Transport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # enum gender: { male: 0, female: 1 }

  self.inheritance_column = :role

  validates :role, presence: true, inclusion: { in: %w[Student Teacher Parent Security SuperAdmin] }

  after_create :send_welcome_email

  has_many :leave_requests
  belongs_to :parent, optional: true
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :square, resize_to_limit: [200, 200]
    attachable.variant :medium, resize_to_limit: [300, 300]
  end


  scope :admin_user, -> {find_by(role: 'SuperAdmin')}

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/lactures_controller.rb
class LacturesController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.role =='Teacher'
      @teacher = Teacher.find(current_user.id)
      @lactures = @teacher.lactures
    elsif current_user.role == 'SuperAdmin'
      @lactures = Lacture.all
    elsif current_user.role == 'Student'
      @attendances = current_user.attendances.where(date: 1.month.ago.to_date..Date.today)
    elsif current_user.role == 'Parent'
      @attendances = current_user.students.first.attendances.where(date: 1.month.ago.to_date..Date.today)
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def show
    @user =User.find(params[:format])
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      redirect_to profiles_show_path(@user), notice: "Profile updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :address, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/profiles/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mb-4">Update Profile</h2>

      <%= form_with(
            scope: :user,
            model: @user,
            url: profile_path(@user),
            method: :patch,
            local: true,
            html: { class: "card p-4 shadow" }
          ) do |f| %>

        <div class="mb-3">
          <%= f.label :avatar, "Profile Photo", class: "form-label" %>
          <%= f.file_field :avatar, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :first_name, "First Name", class: "form-label" %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :last_name, "Last Name", class: "form-label" %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :phone_number, "Phone Number", class: "form-label" %>
          <%= f.text_field :phone_number, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :email, "Email", class: "form-label" %>
          <%= f.text_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :address, "Address", class: "form-label" %>
          <%= f.text_field :address, class: "form-control" %>
        </div>

        
        <div class="text-center">
          <%= f.submit "Update Profile", class: "btn btn-primary w-100  m-b" %>
        </div>
        <div class="text-center mt-2">
          <%=link_to "Cancel",leave_requests_path, class: "btn btn-danger block w-100 ",  aria: { label: 'Cancel' }  %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="row mt-5">
  <div class="col-lg-9">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-content card p-4 shadow">
          <div class="row">
            <div class="col-lg-12">
              <div class="m-b-md text-center ">
                <h2>My Profile</h2>
              </div>
            </div>
          </div>
          <br/>
          <br/>

          <div class="row">
            <div class="col-lg-6">
            <dl class="row mb-0">
                <div class="row mb-3">
            <div class="col-sm-4 text-sm-right">
              <dt>Profile Photo:</dt>
            </div>
            <div class="col-sm-8 text-sm-left">
              <dd class="mb-1">
                <% if @user.avatar.attached? %>
                  <%= image_tag(@user.avatar.variant(:thumb).processed, class: "img-fluid rounded shadow" )%>
                <% else %>
                  <em>No photo uploaded</em>
                <% end %>
              </dd>
            </div>
          </div>

              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>First Name:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @user.first_name %></dd>
                </div>
              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Last Name:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @user.last_name %></dd>
                </div>
              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Email:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @user.email %></dd>
                </div>
              </dl>
              <% if current_user.role == 'Student' %>
                <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Enrollment Number:</dt></div>
                  <div class="col-sm-8 text-sm-left">
                    <dd class="mb-1"><%= @user.roll_no %></dd>
                  </div>
                </dl>
                <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Qualification:</dt></div>
                  <div class="col-sm-8 text-sm-left">
                    <dd class="mb-1"><%= @user.qualification %></dd>
                  </div>
                </dl>
                <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Roll No:</dt></div>
                  <div class="col-sm-8 text-sm-left">
                    <dd class="mb-1"><%= @user.roll_no %></dd>
                  </div>
                </dl>
                <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Parent Name:</dt></div>
                  <div class="col-sm-8 text-sm-left">
                    <dd class="mb-1"><%= @user.parent&.full_name %></dd>
                  </div>
                </dl>
                  <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Parent phone:</dt></div>
                  <div class="col-sm-8 text-sm-left">
                    <dd class="mb-1"><%= @user.parent&.phone_number %></dd>
                  </div>
                </dl>
              <% end %>
              <%if current_user.role == 'Teacher'%>
                <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Qualification:</dt></div>
                  <div class="col-sm-8 text-sm-left">
                    <dd class="mb-1"><%= @user.qualification %></dd>
                  </div>
                </dl>
                <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Experience:</dt></div>
                    <div class="col-sm-8 text-sm-left">
                      <dd class="mb-1"><%= @user.experience_years %></dd>
                    </div>
                </dl>
                 <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Join On:</dt></div>
                    <div class="col-sm-8 text-sm-left">
                      <dd class="mb-1"><%= @user.joining_date %></dd>
                    </div>
                </dl>
              <%end%>
            </div>

            <div class="col-lg-6">
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Phone Number:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @user.phone_number %></dd>
                </div>
              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Date of Birth:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @user.date_of_birth %></dd>
                </div>
              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Gender:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @user.gender %></dd>
                </div>
              </dl>
                <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Address:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @user.address %></dd>
                </div>
              </dl>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="wrapper wrapper-content project-manager">
      <h4>Profile Actions</h4>
      <div class="text-center m-t-md">
        <div class="row">
          <div class="col-lg-12">
            <%= link_to edit_profile_path(@user), class: "btn btn-block btn-primary m-b-sm" do %>
              <i class="fa fa-edit"></i> Edit Profile
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "accro2.png", class: "d-block w-100", alt: "Image 1" %>
      <div class="carousel-caption d-none d-md-block" style="background-color: rgba(255, 255, 255, 0.3); color: black; min-height: 100vh;  display: flex; justify-content: center; align-items: flex-start;  margin: 0;text-align: left;">
        <% if current_user.role == 'SuperAdmin' %>
          <h2 style="color: black; text-align: center;">Admin Responsibilities</h2>
          <ul style="color: black;">
                      <br>

            <li><h4>Manage all types of Users (students, parents, teachers)</h4></li>
            <br>
            <li><h4>Assign class rolls and lectures to students</h4></li>            <br>
            <li><h4>Create and manage student attendance</h4></li>            <br>
            <li><h4>Approve student leaves</h4></li><br>
            <li><h4>Configure system settings</h4></li><br>
            <li><h4>View all data</h4></li><br>
          </ul>
        <% elsif current_user.role == 'Student' %>
          <h2 style="color: black; text-align: center;">Your Responsibilities</h2>
          <ul style="color: black;">
            <li><h4>Apply for leave</h4></li><br>
            <li><h4>View attendance</h4></li><br>
            <li><h4>View profile</h4></li><br>
            <li><h4>Edit your profile</h4></li><br>
            <li><h4>Apply for early leave</h4></li><br>
          </ul>
        <% elsif current_user.role == 'Teacher' %>
          <h2 style="color: black; text-align: center;">Your Responsibilities</h2>
          <ul style="color: black;">
            <li><h4>View students' leave requests</h4></li><br>
            <li><h4>Approve or reject leaves</h4></li><br>
            <li><h4>View total number of leaves</h4></li><br>
            <li><h4>View your lectures</h4></li><br>
            <li><h4>Mark student attendance according to lectures</h4></li><br>
            <li><h4>Update your profile</h4></li><br>
          </ul>
        <% elsif current_user.role == 'Parent' %>
          <h2 style="color: black; text-align: center;">Your Responsibilities</h2>
          <ul style="color: black;">
            <li><h4>Update your profile</li></h4><br>
            <li><h4>View your student's attendance</li></h4><br>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "accro.png", class: "d-block w-100", alt: "Image 2" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "accro5.jpeg", class: "d-block w-100", alt: "Image 3" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>