config/routes.rb
Rails.application.routes.draw do
  get "attendances/index"

  namespace :admin do
    # resources :users
    resources :students
    resources :teachers
    resources :parents
    resources :transports
    # resources :leave_request
    resources :securities
    resources :class_rooms
    resources :lactures
    resources :attendances
    root to: "students#index"
  end

  get "teachers/scaffold"
  get "students/index"
  get "students/new"
  get "students/edit"
  get "profiles/index"
  get "profiles/show"
  get "welcome/index"
  devise_for :users, controllers: {
    sessions: 'users/sessions' ,
    # Tell Devise to use the overridden controller
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :students
  resources :teachers
  resources :class_rooms
  resources :lactures do
    resources :attendances
  end
  
  resources :leave_requests do
    collection do
      post :apply_early_leave, to: 'leave_requests#create_early_leave'
      get  :apply_early_leave, to: 'leave_requests#apply_early_leave'
    end
    member do
      patch :update_status
      get :update_status  # temporary
    end
  end
  resources :profiles
  root "welcome#index"
end

app/models/leave_request.rb
class LeaveRequest < ApplicationRecord
  has_many :users, class_name: 'User', foreign_key: 'approval_id'
  belongs_to :user

  enum :status, { pending: 0, approved: 1, cancelled: 2 }
  enum :leave_type, {full_day: 0, half_day: 1}
  enum :transport, {College_transport: 0, own_vahicle: 1}

  STATUS_COLORS = {
    'approved' => 'success',
    'pending' => 'warning',
    'cancelled' => 'danger'
  }.freeze

  after_create :send_email_for_approval

  def send_email_for_approval
    UserMailer.send_email_for_approval(self, User.admin_user).deliver_now
  end
end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_leave_request, only: [:show, :edit, :update, :destroy, :update_status]

  def index
    @leaves = current_user.leave_requests
    @total_leaves = current_user.leave_requests.count
    @total_approved_leaves = current_user.leave_requests.where(status: :approved).count
    @total_pending_leaves = current_user.leave_requests.where(status: :pending).count
    @total_cancelled_leaves = current_user.leave_requests.where(status: :cancelled).count

    @leaves = LeaveRequest.all
    @total_leaves = LeaveRequest.all.count
    @total_approved_leaves = LeaveRequest.where( status: :approved).count
    @total_pending_leaves = LeaveRequest.where( status: :pending).count
    @total_cancelled_leaves = LeaveRequest.where( status: :cancelled).count

    if current_user.role == 'Teacher'
      @leaves = LeaveRequest.where(approval_id: current_user.id)
      @total_leaves = LeaveRequest.where(approval_id: current_user.id).count
      @total_approved_leaves = LeaveRequest.where(approval_id: current_user.id, status: :approved).count
      @total_pending_leaves = LeaveRequest.where(approval_id: current_user.id, status: :pending).count
      @total_cancelled_leaves = LeaveRequest.where(approval_id: current_user.id, status: :cancelled).count
    end

    if current_user.role == 'SuperAdmin'
      @leaves = LeaveRequest.all
      @total_leaves = LeaveRequest.all.count
      @total_approved_leaves = LeaveRequest.where(status: :approved).count
      @total_pending_leaves = LeaveRequest.where( status: :pending).count
      @total_cancelled_leaves = LeaveRequest.where( status: :cancelled).count
    end

    if current_user.role == 'Parent'
      student = current_user.students.first
      @leaves = LeaveRequest.where(user_id: student.id)
      @total_leaves = LeaveRequest.where(user_id: student.id).count
      @total_approved_leaves = LeaveRequest.where(user_id: student.id, status: :approved).count
      @total_pending_leaves = LeaveRequest.where(user_id: student.id, status: :pending).count
      @total_cancelled_leaves = LeaveRequest.where(user_id: student.id, status: :cancelled).count
    end

    if current_user.role == 'Teacher'
      @leaves = LeaveRequest.where(approval_id: current_user.id)
      @total_leaves = LeaveRequest.where(approval_id: current_user.id).count
      @total_approved_leaves = LeaveRequest.where(approval_id: current_user.id, status: :approved).count
      @total_pending_leaves = LeaveRequest.where(approval_id: current_user.id, status: :pending).count
      @total_cancelled_leaves = LeaveRequest.where(approval_id: current_user.id, status: :cancelled).count
    end
  end

  def show
    @total_leaves = current_user.leave_requests.count
    @total_approved_leaves = current_user.leave_requests.where(status: :approved).count
    @total_pending_leaves = current_user.leave_requests.where(status: :pending).count
    @total_cancelled_leaves = current_user.leave_requests.where(status: :cancelled).count

    if current_user.role == 'Teacher'
      @leaves = LeaveRequest.where(approval_id: current_user.id)
      @total_leaves = LeaveRequest.where(approval_id: current_user.id).count
      @total_approved_leaves = LeaveRequest.where(approval_id: current_user.id, status: :approved).count
      @total_pending_leaves = LeaveRequest.where(approval_id: current_user.id, status: :pending).count
      @total_cancelled_leaves = LeaveRequest.where(approval_id: current_user.id, status: :cancelled).count
    end

    if current_user.role == 'SuperAdmin'
      @leaves = LeaveRequest.all
      @total_leaves = LeaveRequest.where(user_id: @leave.user.id).count
      @total_approved_leaves = LeaveRequest.where(status: :approved, user_id: @leave.user.id).count
      @total_pending_leaves = LeaveRequest.where( status: :pending, user_id: @leave.user.id).count
      @total_cancelled_leaves = LeaveRequest.where( status: :cancelled, user_id: @leave.user.id).count
    end
  end

  def new
    @leave = current_user.leave_requests.new
    @students = Student.all
  end

  def create
    @leave = current_user.leave_requests.new(leave_request_params)

    if @leave.save
      redirect_to leave_requests_path, notice: 'Leave request was successfully created.'
    else
      render :new
    end
  end

  def apply_early_leave
    @leave = current_user.leave_requests.new
    @students = Student.all
  end

  def create_early_leave
    @leave = current_user.leave_requests.new(leave_request_params)

    if @leave.save
      redirect_to leave_requests_path, notice: 'Leave request was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @leave.update(leave_request_params)
      redirect_to leave_requests_path, notice: 'Leave request was successfully updated.'
    else
      render :edit
    end
  end

  def update_status
    if @leave.update(status: params[:status])
      redirect_to leave_request_path(@leave), 
                  notice: "Leave request was successfully #{params[:status]}."
       UserMailer.send_email_update_status(@leave, @leave.user).deliver_now
       UserMailer.send_email_for_early_leave_approval(@leave).deliver_now if @leave.transport.present?
    else
      redirect_to leave_request_path(@leave),
                  alert: "Failed to update leave status: #{@leave.errors.full_messages.to_sentence}"
    end
  end

  def destroy
    @leave.destroy
    redirect_to leave_requests_path, notice: 'Leave request was successfully deleted.'
  end

  private

  def set_leave_request
    @leave = LeaveRequest.find(params[:id])
  end

  def leave_request_params
    params.require(:leave_request).permit(:form_date, :to_date, :reason, :leave_type, :request_id, :approval_id, :status, :transport)
  end
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/views/leave_requests/apply_early_leave.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mb-4">Apply For Early Leave</h2>

      <%= form_with(model: @leave, local: true, html: { class: "card p-4 shadow" }) do |f| %>

        <% if current_user.role == 'SuperAdmin' %>
          <div class="mb-3">
            <%= f.label :student_id, "Select Student by Email", class: "form-label" %>
            <%= f.select :student_id, @students.map { |obj| [obj.email, obj.id] },
              { prompt: 'Select Student by email...' },
              { class: 'form-control', aria: { label: 'Select Student' } } %>
          </div>
        <% else %>
          <%= f.hidden_field :request_id, value: current_user.id %>
        <% end %>

        <%if current_user.role == 'Teacher'%>
            <%= f.hidden_field :approval_id, value: SuperAdmin.first.id %>

        <%else%>
          <div class="mb-3">
            <%= f.label :approval_id, "Approval By", class: "form-label" %>
            <%= f.select :approval_id, Teacher.all.map { |t| [t.email, t.id] }, class: "form-select" %>
          </div>
        <%end%>

        <div class="mb-3">
          <%= f.label :transport, "Transport", class: "form-label" %>
          <%= f.select :transport, LeaveRequest.transports.map { |key, value| [key.to_s.titleize, key] }, class: "form-select" %>
        </div>

        <div class="mb-3">
          <%= f.label :reason, "Reason for Leave", class: "form-label" %>
          <%= f.text_area :reason, class: "form-control", rows: 3 %>
        </div>

        <%=f.hidden_field :form_date, value: Date.today%>
        <%=f.hidden_field :to_date, value: Date.today%>
        <%=f.hidden_field :leave_type, value: :half_day%>
        <%=f.hidden_field :apply_early_leave, value: 'true'%>


        <div class="text-center">
          <%= f.submit "Submit Leave Request", class: "btn btn-primary w-100  m-b" %>
        </div>
        <div class="text-center mt-2">
          <%=link_to "Cancel",leave_requests_path, class: "btn btn-danger block w-100 ",  aria: { label: 'Cancel' }  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/leave_requests/index.html.erb
 <% if flash[:error].present? %>
      <p class='flash-error'><%= flash[:error] %></p>
    <% end %>
    <% if flash[:success].present? %>
      <p class='flash-success'><%= flash[:success] %></p>
    <% end %>
<div class="container mt-4" >
<div class="row">
  <div class="col-md-3">
    <div class="ibox" style="background-color: white; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
      <div class="ibox-title d-flex justify-content-between align-items-center">
        <h5 class="m-0">Total Leaves</h5>
        <div class="ibox-tools">
          <span class="badge bg-primary float-end">Total</span>
        </div>
      </div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= @total_leaves %></h1>
      </div>
    </div>
  </div>
    <div class="col-md-3">
    <div class="ibox" style="background-color: white; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
      <div class="ibox-title d-flex justify-content-between align-items-center">
        <h5 class="m-0">Total Approved Leaves</h5>
        <div class="ibox-tools">
          <span class="badge bg-success float-end">Total</span>
        </div>
      </div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= @total_approved_leaves %></h1>
      </div>
    </div>
  </div>
    <div class="col-md-3">
    <div class="ibox" style="background-color: white; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
      <div class="ibox-title d-flex justify-content-between align-items-center">
        <h5 class="m-0">Total Pending Leaves</h5>
        <div class="ibox-tools">
          <span class="badge bg-warning float-end">Total</span>
        </div>
      </div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= @total_pending_leaves %></h1>
      </div>
    </div>
  </div>
    <div class="col-md-3">
    <div class="ibox" style="background-color: white; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
      <div class="ibox-title d-flex justify-content-between align-items-center">
        <h5 class="m-0">Total Cancelled Leaves</h5>
        <div class="ibox-tools">
          <span class="badge bg-danger float-end">Total</span>
        </div>
      </div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= @total_cancelled_leaves %></h1>
      </div>
    </div>
  </div>
</div>
</div>
<div class="container mt-4" >
 

  <div class="row">
     <div class="row align-items-center mb-4">
     <%if current_user.role == 'Student' || current_user.role == 'SuperAdmin'%>
    <div class="col-md-6">
      <h2 class="mb-0">My Leaves</h2>
    </div>
    
      <div class="col-md-6 text-end">
        <%= link_to "Apply Leave", new_leave_request_path, class: "btn btn-primary" %>
      </div>
    <%end%>
    <%if current_user.role == 'Teacher'%>
      <div class="col-md-6">
        <h2 class="mb-0">Students Leaves</h2>
      </div>
    <%end%>
       <%if current_user.role == 'Parent'%>
      <div class="col-md-6">
        <h2 class="mb-0">Leave Applications for Your Child</h2>
      </div>
    <%end%>
  </div>
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <thead class="table-dark">
            <tr>
            <th> Student Name </th>
              <th>From Date</th>
              <th>To Date</th>
              <th>Reason</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @leaves.each_with_index do |leave, index| %>
         <tr onclick="window.location='<%= leave_request_path(leave) %>'" style="cursor: pointer;">
                <td><%=leave.user.full_name%></td>
                <td><%= leave.form_date %></td>
                <td><%= leave.to_date %></td>
                <td><%= leave.reason %></td>
                <td><span class="badge bg-<%= LeaveRequest::STATUS_COLORS[leave.status] %>"><%= leave.status %></span></td>              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/leave_requests/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mb-4">Apply Leave</h2>

      <%= form_with(model: @leave, local: true, html: { class: "card p-4 shadow" }) do |f| %>
        
        <% if current_user.role == 'SuperAdmin' %>
          <div class="mb-3">
            <%= f.label :student_id, "Select Student by Email", class: "form-label" %>
            <%= f.select :student_id, @students.map { |obj| [obj.email, obj.id] },
              { prompt: 'Select Student by email...' },
              { class: 'form-control', aria: { label: 'Select Student' } } %>
          </div>
        <% else %>
          <%= f.hidden_field :request_id, value: current_user.id %>
        <% end %>

        <div class="mb-3">
          <%= f.label :form_date, "From Date", class: "form-label" %>
          <%= f.date_field :form_date, min: Date.today, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :to_date, "To Date", class: "form-label" %>
          <%= f.date_field :to_date, min: Date.today, class: "form-control" %>
        </div>

        <div class= "mb-3">
          <%= f.label :leave_type, "Leave Type", class: "for,=label"%>
          <%= f.select :leave_type, LeaveRequest.leave_types.map {|key, value| key}, class: "form-select"%>
        </div>

        <%if current_user.role == 'Teacher'%>
             <div class="mb-3">
            <%= f.label :approval_id, "Approval By", class: "form-label" %>
            <%= f.select :approval_id, SuperAdmin.all.map { |t| [t.email, t.id] }, class: "form-select" %>
          </div>

        <%else%>
          <div class="mb-3">
            <%= f.label :approval_id, "Approval By", class: "form-label" %>
            <%= f.select :approval_id, Teacher.all.map { |t| [t.email, t.id] }, class: "form-select" %>
          </div>
        <%end%>

        <div class="mb-3">
          <%= f.label :reason, "Reason for Leave", class: "form-label" %>
          <%= f.text_area :reason, class: "form-control", rows: 3 %>
        </div>

        <div class="text-center">
          <%= f.submit "Submit Leave Request", class: "btn btn-primary w-100  m-b" %>
        </div>
        <div class="text-center mt-2">
          <%=link_to "Cancel",leave_requests_path, class: "btn btn-danger block w-100 ",  aria: { label: 'Cancel' }  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/leave_requests/show.html.erb
 <div class="container mt-4" >
<div class="row">
  <div class="col-md-3">
    <div class="ibox" style="background-color: white; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
      <div class="ibox-title d-flex justify-content-between align-items-center">
        <h5 class="m-0">Total Leaves</h5>
        <div class="ibox-tools">
          <span class="badge bg-primary float-end">Total</span>
        </div>
      </div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= @total_leaves %></h1>
      </div>
    </div>
  </div>
    <div class="col-md-3">
    <div class="ibox" style="background-color: white; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
      <div class="ibox-title d-flex justify-content-between align-items-center">
        <h5 class="m-0">Total Approved Leaves</h5>
        <div class="ibox-tools">
          <span class="badge bg-success float-end">Total</span>
        </div>
      </div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= @total_approved_leaves %></h1>
      </div>
    </div>
  </div>
    <div class="col-md-3">
    <div class="ibox" style="background-color: white; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
      <div class="ibox-title d-flex justify-content-between align-items-center">
        <h5 class="m-0">Total Pending Leaves</h5>
        <div class="ibox-tools">
          <span class="badge bg-warning float-end">Total</span>
        </div>
      </div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= @total_pending_leaves %></h1>
      </div>
    </div>
  </div>
    <div class="col-md-3">
    <div class="ibox" style="background-color: white; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
      <div class="ibox-title d-flex justify-content-between align-items-center">
        <h5 class="m-0">Total Cancelled Leaves</h5>
        <div class="ibox-tools">
          <span class="badge bg-danger float-end">Total</span>
        </div>
      </div>
      <div class="ibox-content">
        <h1 class="no-margins"><%= @total_cancelled_leaves %></h1>
      </div>
    </div>
  </div>
</div>
 <% if flash[:error].present? %>
      <p class='flash-error'><%= flash[:error] %></p>
    <% end %>
    <% if flash[:success].present? %>
      <p class='flash-success'><%= flash[:success] %></p>
    <% end %>



<div class="row mt-5">
  <div class="col-lg-9">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-content card p-4 shadow">
          <div class="row">
            <div class="col-lg-12">
              <div class="m-b-md">
                <h2>Leave Request</h2>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-6">
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>First Name:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%=@leave.user.first_name%></dd>
                </div>
              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Last Name:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%=@leave.user.last_name%></dd>
                </div>
              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Email:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%=@leave.user.email%></dd>
                </div>
              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Phone Number:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @leave.user.phone_number %>
                  </dd>
                </div>
              </dl>
               <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Leave Type:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @leave.leave_type %>
                  </dd>
                </div>
              </dl>
               <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Approval:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= User.find(@leave.approval_id).full_name %>
                  </dd>
                </div>
              </dl>   <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Parent Phone Number:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%=@leave.user&.parent&.phone_number %>
                  </dd>
                </div>
              </dl>
            </div>

            <div class="col-lg-6">
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>From Date:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%=@leave.form_date%></dd>
                </div>
              </dl>
              <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>To date:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @leave.to_date %></dd>
                </div>
              </dl>
                <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Reason:</dt></div>
                <div class="col-sm-8 text-sm-left">
                  <dd class="mb-1"><%= @leave.reason %></dd>
                </div>
              </dl>
              <%if @leave.transport.present?%>
                </dl>
                  <dl class="row mb-0">
                  <div class="col-sm-4 text-sm-right"><dt>Reason:</dt></div>
                  <div class="col-sm-8 text-sm-left">
                    <dd class="mb-1"><%= @leave.transport %></dd>
                  </div>
                </dl>
              <%end%>

               </dl>
                <dl class="row mb-0">
                <div class="col-sm-4 text-sm-right"><dt>Status:</dt></div>
                <div class="col-sm-8 text-sm-left">
             <div>
                <span class="badge bg-<%= LeaveRequest::STATUS_COLORS[@leave.status] %>"><%= @leave.status %></span>
              </div>
                          
              </div>
              </dl>
            </div>
            <div>
         
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%if current_user.role == 'Teacher'|| current_user.role =='SuperAdmin' && @leave.status != 'approved'%>
    <div class="col-lg-3">
    <div class="wrapper wrapper-content project-manager">
      <h4>Leave Approval Actions</h4>
      <div class="text-center m-t-md">
        <div class="row">
          <div class="col-lg-12">
            <%= button_to "Approve",
                update_status_leave_request_path(@leave, status: 'approved'),
                method: :patch,
                class: "btn btn-block btn-success m-b-sm" %>
          </div>
        </div>
      </div>
      
      <div class="text-center m-t-md mt-2">
        <div class="row">
          <div class="col-lg-12">
            <%= link_to update_status_leave_request_path(@leave, status: 'cancelled'), 
                method: :patch, 
                class: "btn btn-block btn-danger m-b-sm" do %>
              <i class="fa fa-times"></i> Cancel
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%end%>
</div>
</div>