config/routes.rb
Rails.application.routes.draw do
  get "attendances/index"

  namespace :admin do
    # resources :users
    resources :students
    resources :teachers
    resources :parents
    resources :transports
    # resources :leave_request
    resources :securities
    resources :class_rooms
    resources :lactures
    resources :attendances
    root to: "students#index"
  end

  get "teachers/scaffold"
  get "students/index"
  get "students/new"
  get "students/edit"
  get "profiles/index"
  get "profiles/show"
  get "welcome/index"
  devise_for :users, controllers: {
    sessions: 'users/sessions' ,
    # Tell Devise to use the overridden controller
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :students
  resources :teachers
  resources :class_rooms
  resources :lactures do
    resources :attendances
  end
  
  resources :leave_requests do
    collection do
      post :apply_early_leave, to: 'leave_requests#create_early_leave'
      get  :apply_early_leave, to: 'leave_requests#apply_early_leave'
    end
    member do
      patch :update_status
      get :update_status  # temporary
    end
  end
  resources :profiles
  root "welcome#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
  belongs_to :lacture

  enum :status, {present: 0, absent: 1}
  STATUS_COLORS = {
    'present' => 'success',
    'absent' => 'danger'
  }.freeze
end

app/models/class_room.rb
class ClassRoom < ApplicationRecord
  has_many :students
  has_many :lactures
  enum :year, {first_year: 0, second_year: 1, third_year: 2, fourth_yaar: 3}
end

app/models/lacture.rb
class Lacture < ApplicationRecord
  belongs_to :teacher
  belongs_to :class_room
  has_many :attendances
end

app/models/leave_request.rb
class LeaveRequest < ApplicationRecord
  has_many :users, class_name: 'User', foreign_key: 'approval_id'
  belongs_to :user

  enum :status, { pending: 0, approved: 1, cancelled: 2 }
  enum :leave_type, {full_day: 0, half_day: 1}
  enum :transport, {College_transport: 0, own_vahicle: 1}

  STATUS_COLORS = {
    'approved' => 'success',
    'pending' => 'warning',
    'cancelled' => 'danger'
  }.freeze

  after_create :send_email_for_approval

  def send_email_for_approval
    UserMailer.send_email_for_approval(self, User.admin_user).deliver_now
  end
end

app/models/parent.rb
class Parent < User
  has_many :students
end

app/models/security.rb
class Security < User
end

app/models/student.rb
class Student < User
  belongs_to :parent, optional: true
  belongs_to :class_room, optional: true
  has_many :attendances

  def parent_email
    parent&.email
  end

  def parent_email=(email)
    found_parent = Parent.find_by(email: email)
    if found_parent
      self.parent = found_parent
    else
      errors.add(:parent_email, "not found")
    end
  end
end

app/models/super_admin.rb
class SuperAdmin < User
end

app/models/teacher.rb
class Teacher < User
  has_many :lactures
end

app/models/transport.rb
class Transport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # enum gender: { male: 0, female: 1 }

  self.inheritance_column = :role

  validates :role, presence: true, inclusion: { in: %w[Student Teacher Parent Security SuperAdmin] }

  after_create :send_welcome_email

  has_many :leave_requests
  belongs_to :parent, optional: true
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :square, resize_to_limit: [200, 200]
    attachable.variant :medium, resize_to_limit: [300, 300]
  end


  scope :admin_user, -> {find_by(role: 'SuperAdmin')}

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "College Management App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>



    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: "all" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
        
    <%= javascript_importmap_tags %> 
  </head>

  <body style="background-color: #E5E4E2;  position: relative; min-height: 100vh;"> 
    <%if current_user.present?%>
      <nav class="navbar navbar-expand-lg navbar-light custom-navbar">
          <%= link_to welcome_index_path, class: "navbar-brand text-white" do %>
            <%= "#{current_user.role} Portal" %>
          <% end %>   
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <span class="navbar-text sign-out-link d-flex align-items-center justify-content-end">
          <%unless  current_user.role == 'Security' %>
              <%= link_to 'Attendance', lactures_path, class: 'text-white me-3' %>
          <%end%>
            <%if current_user.role == 'SuperAdmin'%>
              <%= link_to 'Admin Users', admin_students_path, class: 'text-white me-3' %>
               <%end%>
              <div class="dropdown">
                <button 
                  class="btn text-white dropdown-toggle" 
                  id="dropdownMenuButton" 
                  data-bs-toggle="dropdown" 
                  aria-expanded="false">
                  Leaves
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li> <a class="dropdown-item" href="/leave_requests">All Leaves</a>
                  <%unless current_user.role == 'Parent' || current_user.role == 'Security'%>
                    <a class="dropdown-item label-white" href="/leave_requests/new">Apply for Planned Leave</a>
                    <%unless current_user.role == 'Teacher'%>
                    <a class="dropdown-item" href="/leave_requests/apply_early_leave">Apply for Early Leave</a></li>
                    <%end%>
                  <%end%>
                </ul>
              </div>

              <%= link_to 'Profile', profiles_show_path(current_user), class: ' text-white me-3' %>
              <%= link_to 'Sign Out', destroy_user_session_path, class: 'btn text-white' %>
            </span>
        </div>
      </nav>
    <%else%>

    <%end%>
    <%= yield %>
  
  <%if current_user.present?%>
    <footer style="position: absolute; bottom: 0; width: 100%; height: 100px;">
      <%= render "shared/footer" %>
    </footer>
    <%end%>
<!-- Include the footer -->

  </body>
</html>
 

app/views/shared/_footer.html.erb
<footer style="background-color: #333; color: white; text-align: center; padding: 20px; width: 100%;">
  <p>&copy; <%= Time.current.year %> College Management System. All rights reserved.</p>
  
  <!-- Social Media Icons -->
      
</footer>
 